#!/usr/bin/env bash

REPO_PATH="$HOME/.config/nvim"
cd "$REPO_PATH" || exit 1

if [ -n "$(git status --porcelain)" ]; then
    git add .
    git commit -m "auto_config_update"
    git push origin main
else
    echo "No changes to commit."
fi


